### ISSUE TITLE
retest ?

### ISSUE THREAD

**Issue by mk01** [xbianonpi/xbian-package-cec#3]
@mkreisl 

I took what you did, merged into rebased master onto PE/master and cleaned/removed.
so can you recheck ?

in case there is something to fix after to get it working as you did before, directly edit src tree at xbian-sources-libcec. don't hesitate. 

thx

**Comment by mkreisl** [comment]
@mk01 
Sure, will do it tomorrow

**Comment by mkreisl** [comment]
@mk01 
Done!

**Comment by mkreisl** [comment]
@mk01 
I noticed you made some more changes since my last test. 
But unfortunately it does not build the package with RPi or iMX support.
```
-- Pulse-Eight CEC Adapter:                yes
-- Pulse-Eight CEC Adapter detection:      yes
-- lockdev support:                        yes
-- xrandr support:                         no
-- Raspberry Pi support:                   no
-- TDA995x support:                        no
-- Exynos support:                         no
-- i.MX6 support:                          no
-- Python support:                         version 2.7.9 (2.7)
```
And, running the command `patch` always runs into an error
```
PROCESSING imx6-cec3
-------------------------------
find: "./imx6-cec3": Datei oder Verzeichnis nicht gefunden
checking ./inject-metapackage-with-xbian.patch
patch: **** malformed patch at line 13:  

! won't patch with ./inject-metapackage-with-xbian.patch
```
Maybe you didn't push all your commits
(before you ask, I already updated package xbian)

**Comment by mkreisl** [comment]
You have to set HAVE_RPI_API and/or HAVE_IMX_API to 1 for cmake, it will not be done automatically because you eliminated the autodetection of RPI-Libs, for IMX there was never an autodetection mechanism.

**Comment by mk01** [comment]
@mkreisl 

good you run the compilation. me not for RPI. but actually this is what I meant - pushed the missing line.
also fixed the patch. it had wrong line index.

**Comment by mk01** [comment]
@mkreisl 

I also fixed xbian-update (in advance) and it's dependencies around libcec (apt was again trying to remove all xbian packages) and also updated and pushed xbian-repo package with putting also libcec* into packages whose XBIAN hosted versions have top prio for installing.

imx6 jessie then nicely upgraded to new packages. maybe you can test the same for RPI (feel free to put debs in devel repo for this testing).

because XBMC needs to be relinked, we can't launch just by those libcec upgrades, but we can start planning recompiling the older XBMCs and stuff.

**Comment by mkreisl** [comment]
@mk01 
> (feel free to put debs in devel repo for this testing).

Still don't know how to do that.I looked a little bit around the servers and found a folder structure on xbian.dehakkelaar.nl:/web/.upload and a script called .update.sh - am I on the right way?
For imx6-jessie there are already the latest libcec3 packages ;-) ...
